# Generated by Django 5.1.6 on 2025-04-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], default='A', max_length=1)),
                ('total', models.IntegerField(default=0)),
                ('game1', models.IntegerField(default=0)),
                ('game2', models.IntegerField(default=0)),
                ('game3', models.IntegerField(default=0)),
                ('game4', models.IntegerField(default=0)),
                ('game5', models.IntegerField(default=0)),
                ('game6', models.IntegerField(default=0)),
                ('game7', models.IntegerField(default=0)),
                ('game8', models.IntegerField(default=0)),
                ('game9', models.IntegerField(default=0)),
                ('game10', models.IntegerField(default=0)),
                ('game11', models.IntegerField(default=0)),
                ('game12', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
